# Deps for install
tap "homebrew/bundle"
tap "homebrew/core"
tap "homebrew/cask-fonts"
  cask "font-source-code-pro-for-powerline"
brew "mas"

# General dev
# Dep libs
brew "cmake"
brew "cocoapods" # For iOS dev
brew "libpng" # Lib for processing PNG files
brew "ragel" # Lib for text parsing and input validation
brew "git"
brew "imagemagick" # For image processing
brew "asdf"
  # Deps for asdf nodejs
  # Read more to setup: https://github.com/asdf-vm/asdf-nodejs
  brew "coreutils"
  brew "gpg"
  # For Erlang/Elixir
  brew "autoconf" # Build tool
  brew "wxmac" # Observer/Debugger

# Cli thing
brew "bat" # Better cat
brew "wget"
# zsh
brew "zsh"
  brew "z"
  brew "zsh-syntax-highlighting"
  brew "zsh-history-substring-search"
  brew "zsh-completions"
  brew "zsh-autosuggestions"
brew "shellcheck" # Shell linter
brew "tree"
brew "tmux"
brew "tmux-mem-cpu-load"
brew "httpie"
brew "tldr"
brew "jq"
brew "fd"
brew "fzf"
brew "the_silver_searcher" # ag, grep for code
brew "watchman" # For react-native

# Directory to install
cask_args appdir: "/Applications"
# Cask / GUI
cask "caffeine" # Kepp Mac awake
cask "docker"
cask "dozer" # Hide menu bar icons on macS
cask "google-cloud-sdk"
cask "spectacle" # For tilling window
cask "iterm2"
cask "visual-studio-code"
cask "tableplus" # Tool for Relational Database
cask "brave-browser"
cask "iina" # The modern media player for macOS
cask "itsycal" # Itsycal is a tiny menu bar calendar.
cask "the-unarchiver"
cask "google-backup-and-sync"
cask "typora" # Markdown editor
cask "pock" # Touch Bar widget
cask "android-studio" # Android dev envirment

# Mas
mas "Xcode", id: 497799835
